### ISSUE TITLE
real sending data

### ISSUE THREAD

**Issue by bialystok** [SudoMaker/LoShark#1]
If it working with lora why not put https://reticulum.network/ inside? simple python only needed.
Video with mesh network 3 devices that can send message trought 1 km in city will be great.

Sending data is more than video from test. I need send max bitrate data trought device

**BTW** _is any C library for EFI or similar embeding in any other language like rust, ruby, haskell?_

**Comment by ClassicOldSong** [comment]
It is real sending data.

We don't plan providing python support officially but you can try yourself since it's running Linux. Or you can try implement a JS version of this network as we're running ResonanceJS, our embedded JS runtime as the scripting interface for the LoShark.

**Comment by bialystok** [comment]
I don't know how to write anything. But it seems to me that without a demonstration of a real transmission, then assurances that it works will not be of much use.  It doesn't look easy since the author himself doesn't know how to write such a program. This does not encourage other people to write anything as there is no way to start.

I dont buy a device that has no interface to any known program. for example  pppd, yigdrasill, fAX.25 or others.

I am not talking about an interface to python, but an interface to C.

**Comment by ClassicOldSong** [comment]
Since it is running Linux, you can interface the SX126x chip directly in C.

**Comment by bialystok** [comment]
I can't testing that.. I'm not a hacker. I haven't seen the proof.

I am writing this to show how ordinary people like me think. The kind who would want to buy it. I would like to help but I can't

**Comment by fab1an2** [comment]
meybe this project is good starting point https://github.com/simplyequipped/tcpkissserver

**Comment by ClassicOldSong** [comment]
The LoShark Dashboard is now online. You need a LoShark to see it working in action: https://su.mk/loshark-app

**Comment by fab1an2** [comment]
> You need a LoShark to see it working in action: https://su.mk/loshark-app
I wrote about glue lorashark and reticullum
This is easy and cheap way to jump to reticullum platform
